site_url: https://naughty-shaw-c873f0.netlify.app/
logo_url: https://naughty-shaw-c873f0.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Ativos'
    name: 'actives'
    format: 'json'
    folder: 'content/actives'
    create: true
    slug: '{{ticker}}'
    fields:
      - { label: 'Ticker', name: 'ticker', widget: 'string' }
      - {
          label: 'Tipo',
          name: 'type',
          widget: 'select',
          options:
            [
              'Ação Brasileira',
              'Ação Americana',
              'ETF',
              'Fundo Imobiliário',
              'Criptomoeda',
              'Renda Fixa',
              'Fundo de investimento',
              'Caixa',
              'Outro',
            ],
        }
      - { label: 'Quantidade', name: 'quantity', widget: 'number' }
      - { label: 'Preço médio', name: 'price', widget: 'number', value_type: 'float' }
